// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reflex.proto

package reflexpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamRequest struct {
	Options              *StreamOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	After                string         `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a570507208cc2a2f, []int{0}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetOptions() *StreamOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *StreamRequest) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

type Event struct {
	Type                 int32                `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ForeignId            string               `protobuf:"bytes,5,opt,name=foreign_id,json=foreignId,proto3" json:"foreign_id,omitempty"`
	Id                   string               `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Metadata             []byte               `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_a570507208cc2a2f, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Event) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetForeignId() string {
	if m != nil {
		return m.ForeignId
	}
	return ""
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type StreamOptions struct {
	Lag                  *duration.Duration `protobuf:"bytes,1,opt,name=lag,proto3" json:"lag,omitempty"`
	FromHead             bool               `protobuf:"varint,2,opt,name=fromHead,proto3" json:"fromHead,omitempty"`
	ToHead               bool               `protobuf:"varint,4,opt,name=toHead,proto3" json:"toHead,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StreamOptions) Reset()         { *m = StreamOptions{} }
func (m *StreamOptions) String() string { return proto.CompactTextString(m) }
func (*StreamOptions) ProtoMessage()    {}
func (*StreamOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_a570507208cc2a2f, []int{2}
}

func (m *StreamOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamOptions.Unmarshal(m, b)
}
func (m *StreamOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamOptions.Marshal(b, m, deterministic)
}
func (m *StreamOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamOptions.Merge(m, src)
}
func (m *StreamOptions) XXX_Size() int {
	return xxx_messageInfo_StreamOptions.Size(m)
}
func (m *StreamOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StreamOptions proto.InternalMessageInfo

func (m *StreamOptions) GetLag() *duration.Duration {
	if m != nil {
		return m.Lag
	}
	return nil
}

func (m *StreamOptions) GetFromHead() bool {
	if m != nil {
		return m.FromHead
	}
	return false
}

func (m *StreamOptions) GetToHead() bool {
	if m != nil {
		return m.ToHead
	}
	return false
}

func init() {
	proto.RegisterType((*StreamRequest)(nil), "reflexpb.StreamRequest")
	proto.RegisterType((*Event)(nil), "reflexpb.Event")
	proto.RegisterType((*StreamOptions)(nil), "reflexpb.StreamOptions")
}

func init() { proto.RegisterFile("reflex.proto", fileDescriptor_a570507208cc2a2f) }

var fileDescriptor_a570507208cc2a2f = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x6d, 0x9b, 0x76, 0xdd, 0xe7, 0xd4, 0x11, 0x44, 0x63, 0x41, 0x1d, 0x3d, 0x0d, 0x84,
	0x4e, 0x27, 0x88, 0x47, 0x0f, 0x0a, 0xba, 0x8b, 0x10, 0x3d, 0x2b, 0x19, 0x49, 0x4b, 0x61, 0x5d,
	0x6a, 0x96, 0x0d, 0xfd, 0x9f, 0xfc, 0x23, 0x65, 0x5f, 0xda, 0x0d, 0xdc, 0xad, 0xef, 0x7b, 0x3f,
	0x78, 0xaf, 0x2f, 0xd0, 0x33, 0x2a, 0x9f, 0xa9, 0xef, 0xac, 0x36, 0xda, 0x6a, 0x1a, 0x3b, 0x55,
	0x4f, 0x93, 0xcb, 0x42, 0xeb, 0x62, 0xa6, 0x46, 0x78, 0x9f, 0x2e, 0xf3, 0x91, 0x2d, 0x2b, 0xb5,
	0xb0, 0xa2, 0xaa, 0x1d, 0x9a, 0x5c, 0xfc, 0x07, 0xe4, 0xd2, 0x08, 0x5b, 0xea, 0xb9, 0xf3, 0xd3,
	0x0f, 0x38, 0x78, 0xb3, 0x46, 0x89, 0x8a, 0xab, 0xaf, 0xa5, 0x5a, 0x58, 0x7a, 0x03, 0x1d, 0x5d,
	0xaf, 0x81, 0x05, 0xf3, 0x07, 0xde, 0x70, 0x7f, 0x7c, 0x9a, 0xb5, 0x69, 0x99, 0x23, 0x5f, 0x9d,
	0xcd, 0x5b, 0x8e, 0x1e, 0x43, 0x28, 0x72, 0xab, 0x0c, 0x0b, 0x06, 0xde, 0xb0, 0xcb, 0x9d, 0x98,
	0x90, 0xd8, 0xeb, 0xfb, 0xe9, 0xaf, 0x07, 0xe1, 0xd3, 0x4a, 0xcd, 0x2d, 0xa5, 0x40, 0xec, 0x4f,
	0xad, 0x10, 0x0a, 0x39, 0x7e, 0xd3, 0x7b, 0xe8, 0x6e, 0x0a, 0x33, 0x82, 0x71, 0x49, 0xe6, 0x1a,
	0x67, 0x6d, 0xe3, 0xec, 0xbd, 0x25, 0xf8, 0x16, 0xa6, 0xe7, 0x00, 0xb9, 0x36, 0xaa, 0x2c, 0xe6,
	0x9f, 0xa5, 0x64, 0x21, 0x06, 0x77, 0x9b, 0xcb, 0x8b, 0xa4, 0x87, 0xe0, 0x97, 0x92, 0x45, 0x78,
	0xf6, 0x4b, 0x49, 0x13, 0x88, 0x2b, 0x65, 0x85, 0x14, 0x56, 0xb0, 0xce, 0xc0, 0x1b, 0xf6, 0xf8,
	0x46, 0xbb, 0xa2, 0x13, 0x12, 0xfb, 0xfd, 0x20, 0x5d, 0xb5, 0x73, 0x34, 0x3f, 0x49, 0xaf, 0x20,
	0x98, 0x89, 0x82, 0x79, 0xd8, 0xed, 0x6c, 0xa7, 0xdb, 0x63, 0xb3, 0x26, 0x5f, 0x53, 0xeb, 0x94,
	0xdc, 0xe8, 0xea, 0x59, 0x09, 0x89, 0xe3, 0xc5, 0x7c, 0xa3, 0xe9, 0x09, 0x44, 0x56, 0xa3, 0x43,
	0xd0, 0x69, 0xd4, 0x84, 0xc4, 0x41, 0x9f, 0x8c, 0x1f, 0x20, 0xe2, 0xb8, 0x32, 0xbd, 0x83, 0xc8,
	0x35, 0xa0, 0x3b, 0xc3, 0x37, 0x4f, 0x94, 0x1c, 0x6d, 0x0d, 0x9c, 0x36, 0xdd, 0xbb, 0xf6, 0xa6,
	0x11, 0x76, 0xba, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x38, 0xa0, 0x3f, 0x7d, 0x2a, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReflexClient is the client API for Reflex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReflexClient interface {
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Reflex_StreamClient, error)
}

type reflexClient struct {
	cc *grpc.ClientConn
}

func NewReflexClient(cc *grpc.ClientConn) ReflexClient {
	return &reflexClient{cc}
}

func (c *reflexClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Reflex_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Reflex_serviceDesc.Streams[0], "/reflexpb.Reflex/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &reflexStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Reflex_StreamClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type reflexStreamClient struct {
	grpc.ClientStream
}

func (x *reflexStreamClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReflexServer is the server API for Reflex service.
type ReflexServer interface {
	Stream(*StreamRequest, Reflex_StreamServer) error
}

// UnimplementedReflexServer can be embedded to have forward compatible implementations.
type UnimplementedReflexServer struct {
}

func (*UnimplementedReflexServer) Stream(req *StreamRequest, srv Reflex_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterReflexServer(s *grpc.Server, srv ReflexServer) {
	s.RegisterService(&_Reflex_serviceDesc, srv)
}

func _Reflex_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReflexServer).Stream(m, &reflexStreamServer{stream})
}

type Reflex_StreamServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type reflexStreamServer struct {
	grpc.ServerStream
}

func (x *reflexStreamServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _Reflex_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reflexpb.Reflex",
	HandlerType: (*ReflexServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Reflex_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "reflex.proto",
}
